# Generated by Django 3.2.25 on 2025-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
