# Generated by Django 3.2.25 on 2025-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250610_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='socios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
