# Generated by Django 3.2.25 on 2025-06-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('introduccion', models.TextField()),
                ('imagen', models.URLField(blank=True, null=True)),
                ('historia', models.TextField(blank=True, null=True)),
                ('actualidad', models.TextField(blank=True, null=True)),
                ('socios', models.IntegerField(blank=True, null=True)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
